In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
l=[1,2,3,4,5]

In [6]:
l

[1, 2, 3, 4, 5]

In [7]:
type(l)

list

In [8]:
type(a)

numpy.ndarray

In [11]:
arr=np.array(l)
type(arr)

numpy.ndarray

In [10]:
arr

array([1, 2, 3, 4, 5])

In [12]:
a=np.array([1,2,3,4,5])

In [13]:
a.ndim

1

In [14]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [15]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
b.ndim

2

In [18]:
type(b)

numpy.ndarray

In [23]:
a.dtype

dtype('int32')

In [24]:
a.shape

(5,)

In [25]:
a.ndim

1

In [26]:
a.size

5

In [27]:
a.dtype

dtype('int32')

In [28]:
a=np.zeros(2,dtype=int)

In [29]:
a

array([0, 0])

In [30]:
a=np.zeros(3,dtype=int)

In [31]:
a

array([0, 0, 0])

In [32]:
a=np.zeros(4,dtype=float)
a

array([0., 0., 0., 0.])

In [33]:
a=np.zeros([2,2],dtype=int)
a

array([[0, 0],
       [0, 0]])

In [34]:
a=np.ones([3,4],dtype=int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [35]:
a=np.random.random()
a

0.2975316105576673

In [36]:
a=np.random.random(5)
a

array([0.37217438, 0.53804679, 0.26555086, 0.37027639, 0.85735827])

In [37]:
a.dtype

dtype('float64')

In [41]:
a.size

5

In [42]:
a.shape

(5,)

In [44]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [45]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [48]:
np.__version__

'1.26.1'

In [49]:
arr=np.array([1,2,3,4,5])

In [50]:
arr

array([1, 2, 3, 4, 5])

In [51]:
type(arr)

numpy.ndarray

In [52]:
arr.dtype

dtype('int32')

In [53]:
arr=np.array(42)
arr

array(42)

In [54]:
arr.ndim

0

In [55]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [56]:
arr.ndim

1

In [57]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
arr.ndim

2

In [59]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [60]:
arr = np.array([1, 2, 3, 4], ndmin=5)
arr

array([[[[[1, 2, 3, 4]]]]])

In [62]:
arr=np.array([1,2,3,4,5],ndmin=3)
arr

array([[[1, 2, 3, 4, 5]]])

In [65]:
arr.ndim

3

In [66]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [67]:
arr[0]

1

In [68]:
arr[1]

2

In [69]:
arr[0]+arr[1]

3

In [70]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [71]:
arr[0,0]

1

In [72]:
arr[0,1]

2

In [73]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [74]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [75]:
arr=np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [84]:
arr=np.array([[[1,2,3,4,5],[4,5,6,7,8]],[[1,2,3,4,5],[4,5,16,7,8]]])

In [77]:
arr

array([[[1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8]],

       [[1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8]]])

In [78]:
arr.ndim

3

In [85]:
arr[0,0,0]

1

In [86]:
arr[0,1,2]

6

In [87]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [88]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [89]:
arr[0,-1]

5

In [90]:
arr[1,-1]

10

In [91]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [92]:
arr[0]

1

In [93]:
arr[:]

array([1, 2, 3, 4, 5])

In [94]:
arr[1:]

array([2, 3, 4, 5])

In [95]:
arr[0:-1]

array([1, 2, 3, 4])

In [96]:
arr[1:1]

array([], dtype=int32)

In [97]:
arr[1:-1]

array([2, 3, 4])

In [98]:
arr

array([1, 2, 3, 4, 5])

In [103]:
arr[-4:-1]

array([2, 3, 4])

In [104]:
arr[-3:-1]

array([3, 4])

In [105]:
arr

array([1, 2, 3, 4, 5])

In [106]:
arr[::1]

array([1, 2, 3, 4, 5])

In [107]:
arr[::2]

array([1, 3, 5])

In [108]:
arr[1:5:2]

array([2, 4])

In [109]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [110]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [111]:
arr[1,1]

7

In [112]:
arr[1,:]

array([ 6,  7,  8,  9, 10])

In [113]:
arr[1,:3]

array([6, 7, 8])

In [114]:
arr[0,:]

array([1, 2, 3, 4, 5])

In [115]:
arr[1,1:3]

array([7, 8])

In [116]:
arr[1,::2]

array([ 6,  8, 10])

In [117]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [119]:
arr[0:2,2]

array([3, 8])

In [120]:
arr[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [121]:
arr.dtype

dtype('int32')

In [123]:
arr=np.array(['qw','qwer','qwert','qwerty'])

In [124]:
arr

array(['qw', 'qwer', 'qwert', 'qwerty'], dtype='<U6')

In [125]:
arr.dtype

dtype('<U6')

In [126]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [127]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [128]:
arr=np.array([1.1,1.2,1.3])

In [129]:
arr

array([1.1, 1.2, 1.3])

In [130]:
arr.dtype

dtype('float64')

In [131]:
arr.shape

(3,)

In [132]:
arr.ndim

1

In [134]:
brr=arr.astype('i')

In [135]:
brr

array([1, 1, 1], dtype=int32)

In [136]:
brr.dtype

dtype('int32')

In [137]:
arr=np.array([-1,0,1])

In [138]:
arr

array([-1,  0,  1])

In [139]:
arr.dtype

dtype('int32')

In [140]:
brr=arr.astype('f')

In [141]:
brr

array([-1.,  0.,  1.], dtype=float32)

In [142]:
brr.dtype

dtype('float32')

In [143]:
crr=brr.astype(bool)

In [144]:
crr

array([ True, False,  True])

In [145]:
crr.dtype

dtype('bool')

In [146]:
arr

array([-1,  0,  1])

In [147]:
a=arr.astype(bool)

In [148]:
a

array([ True, False,  True])

In [149]:
a.dtype

dtype('bool')

In [150]:
a=np.array([1,2,3,4,5])

In [151]:
a

array([1, 2, 3, 4, 5])

In [152]:
a.dtype

dtype('int32')

In [153]:
a[0]

1

In [154]:
b=a.copy()

In [155]:
b

array([1, 2, 3, 4, 5])

In [156]:
b[0]=1000

In [157]:
b

array([1000,    2,    3,    4,    5])

In [158]:
b[0]

1000

In [159]:
a

array([1, 2, 3, 4, 5])

In [160]:
c=a.view()

In [161]:
c

array([1, 2, 3, 4, 5])

In [162]:
c[0]=143

In [163]:
c

array([143,   2,   3,   4,   5])

In [164]:
a

array([143,   2,   3,   4,   5])

In [168]:
print(b.base)

None


In [169]:
print(c.base)

[143   2   3   4   5]


In [170]:
print(a.base)

None


In [171]:
a.shape

(5,)

In [172]:
a

array([143,   2,   3,   4,   5])

In [173]:
a.ndim

1

In [174]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [175]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
a.shape

(9,)

In [181]:
a.size

9

In [182]:
a=a.reshape(3,3)

In [183]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [184]:
a.shape

(3, 3)

In [185]:
a.size

9

In [186]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [187]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [188]:
a.shape

(9,)

In [189]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [190]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [191]:
a=a.reshape(3,3)

In [192]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [193]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [194]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [195]:
a.size

12

In [196]:
a.shape

(12,)

In [197]:
a=a.reshape(2,3,2)

In [198]:
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [199]:
a.shape

(2, 3, 2)

In [200]:
a.ndim

3

In [201]:
arr=np.array([1,2,3,4,5])

In [202]:
arr

array([1, 2, 3, 4, 5])

In [203]:
for i in arr:
    print(i)

1
2
3
4
5


In [204]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [205]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [206]:
for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [207]:
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6


In [208]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [209]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [210]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [213]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
for x in np.nditer(arr[:, ::2]):
  print(x)

[[1 2 3 4]
 [5 6 7 8]]
1
3
5
7


In [216]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [217]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.ndenumerate(arr):
  print(idx, x)

(1, 3) ((0, 0), 1)
(1, 3) ((0, 1), 2)
(1, 3) ((0, 2), 3)
(1, 3) ((0, 3), 4)
(1, 3) ((1, 0), 5)
(1, 3) ((1, 1), 6)
(1, 3) ((1, 2), 7)
(1, 3) ((1, 3), 8)


In [220]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr=np.concatenate((arr1,arr2))


In [221]:
arr

array([1, 2, 3, 4, 5, 6])

In [223]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr=np.concatenate((arr1,arr2),axis=1)

In [224]:
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [225]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr=np.concatenate((arr1,arr2),axis=0)

In [226]:
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [227]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

arr=np.stack((arr1,arr2))

In [228]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [229]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

arr=np.hstack((arr1,arr2))

In [230]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [235]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

arr=np.vstack((arr1,arr2))

In [236]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [237]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [238]:
arr=np.array([1,2,3,4,5,6])

In [239]:
arr

array([1, 2, 3, 4, 5, 6])

In [241]:
brr=np.array_split(arr,3)

In [242]:
brr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [243]:
crr=np.array_split(arr,4)

In [244]:
crr

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [245]:
for i in brr:
    print(i)

[1 2]
[3 4]
[5 6]


In [246]:
for i in crr:
    print(i)

[1 2]
[3 4]
[5]
[6]


In [247]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [248]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [249]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [250]:
x=np.where(arr==4)
x

(array([3], dtype=int32),)

In [251]:
arr=np.array([1,2,3,4,5,4,4])
arr

array([1, 2, 3, 4, 5, 4, 4])

In [252]:
x=np.where(arr==4)
x

(array([3, 5, 6], dtype=int32),)

In [254]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [255]:
x=np.where(arr%2==0)
x

(array([1, 3, 5, 7, 9], dtype=int32),)

In [257]:
x=np.where(arr%2==1)
x

(array([0, 2, 4, 6, 8], dtype=int32),)

In [259]:
# The searchsorted() method is assumed to be used on sorted arrays.
# Find the indexes where the value 7 should be inserted:

In [262]:
arr=np.array([1,2,3,5])
print(arr)
x=np.searchsorted(arr,4)
x

[1 2 3 5]


3

In [263]:
arr=np.array([1,2,3,4,5])
print(arr)
x=np.searchsorted(arr,4)
x

[1 2 3 4 5]


3

In [264]:
# Search from right side

In [265]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [266]:
# searchsorted for multiple values

In [267]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [268]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [269]:
arr

array([3, 2, 0, 1])

In [270]:
arr=np.sort(arr)

In [271]:
arr

array([0, 1, 2, 3])

In [272]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [273]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [274]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [277]:
# Filtering Arrays
# Getting some elements out of an existing array and creating a new array out of them is called filtering.

In [278]:
arr = np.array([41, 42, 43, 44])

x = arr[[True, False, True, False]]

print(x)

[41 43]


In [279]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [281]:
from numpy import random
x=random.randint(100)
x

92

In [284]:
from numpy import random
x=random.randint(10)
x

4

In [282]:
x=random.rand()
x

0.7210017027612934

In [285]:
x=random.randint(100,size=5)
x

array([23, 33, 54, 67, 61])

In [286]:
x=random.randint(100,size=(3,5))
x

array([[88, 86, 41, 40, 26],
       [27, 59, 30,  2, 50],
       [94, 59, 52, 39, 92]])

In [287]:
x = random.rand(5)

print(x)

[0.93582891 0.63964852 0.79861626 0.06188329 0.34109904]


In [288]:
x = random.rand(3, 5)

print(x)

[[0.48493353 0.5925591  0.57304961 0.75508472 0.98690146]
 [0.22201695 0.93678398 0.42866328 0.68682191 0.11045564]
 [0.57000652 0.90735252 0.36363735 0.1224074  0.83406646]]


In [289]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [292]:
x=random.choice(arr)
x

2

In [293]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 7 9 9 9]
 [7 9 9 5 3]
 [9 9 5 3 5]]


In [ ]:
# Random Numpy